name: "global-trade-network"

x-type: "hlfv1"
x-loggingLevel: info

description: "The network to be in if you want to stay in the global trade business"

version: 1.0.0

client:

  organization: 78c4b22104de75db92a172ae8fe5e9c6240d2c52

  logging:
    level: info

  peer:
    timeout:
      connection: 10s
      queryResponse: 45s
      executeTxResponse: 120s
  eventService:
    timeout:
      connection: 10s
      registrationResponse: 50s
  orderer:
    timeout:
      connection: 10s
      response: 45s

  cryptoconfig:
    path: /opt/gopath/src/github.com/hyperledger/fabric

  credentialStore:
    path: "/tmp/hfc-kvs"

    cryptoStore:
      path: /tmp/msp

    wallet: wallet-name

  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     ephemeral: false
     level: 256

channels:
  
  channel:
    orderers:
      
      - orderer-843e8145d6d5bacb27802f34494c3860583e0d7e-0.orderer-843e8145d6d5bacb27802f34494c3860583e0d7e.default.svc.cluster.local
      
    peers:
      
      peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52-0.peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52.default.svc.cluster.local:7051:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      
      peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52-1.peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52.default.svc.cluster.local:7051:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      
    chaincodes:
      - chaincodedemo:latest
  
organizations:
  
  78c4b22104de75db92a172ae8fe5e9c6240d2c52:
    mspid: 78c4b22104de75db92a172ae8fe5e9c6240d2c52MSP

    cryptoPath:  C:\Users\86153\Desktop\javasdkdemo_src\config/78c4b22104de75db92a172ae8fe5e9c6240d2c52.peer/msp
    tlsCryptoKeyPath: C:\Users\86153\Desktop\javasdkdemo_src\config/78c4b22104de75db92a172ae8fe5e9c6240d2c52.peer/tls/server.key
    tlsCryptoCertPath: C:\Users\86153\Desktop\javasdkdemo_src\config/78c4b22104de75db92a172ae8fe5e9c6240d2c52.peer/tls/server.crt

    peers:
      
      - peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52-0.peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52.default.svc.cluster.local:7051
      
      - peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52-1.peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52.default.svc.cluster.local:7051
      
  
  ordererorg:
      mspID: "843e8145d6d5bacb27802f34494c3860583e0d7eMSP"

      cryptoPath: C:\Users\86153\Desktop\javasdkdemo_src\config/843e8145d6d5bacb27802f34494c3860583e0d7e.orderer/msp
orderer-eip: 124.70.83.92
orderers:
  
  orderer-843e8145d6d5bacb27802f34494c3860583e0d7e-0.orderer-843e8145d6d5bacb27802f34494c3860583e0d7e.default.svc.cluster.local:
    url: grpcs://124.70.83.92:30805

    grpcOptions:
      ssl-target-name-override: orderer-843e8145d6d5bacb27802f34494c3860583e0d7e-0.orderer-843e8145d6d5bacb27802f34494c3860583e0d7e.default.svc.cluster.local
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: C:\Users\86153\Desktop\javasdkdemo_src\config/843e8145d6d5bacb27802f34494c3860583e0d7e.orderer/msp/tlscacerts/tlsca.843e8145d6d5bacb27802f34494c3860583e0d7e-cert.pem
  
peers:
  
  
  
  peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52-0.peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52.default.svc.cluster.local:7051:
  
  
    
    url: grpcs://124.70.83.92:30605
    
    grpcOptions:
      ssl-target-name-override: peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52-0.peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52.default.svc.cluster.local
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: C:\Users\86153\Desktop\javasdkdemo_src\config/78c4b22104de75db92a172ae8fe5e9c6240d2c52.peer/msp/tlscacerts/tlsca.78c4b22104de75db92a172ae8fe5e9c6240d2c52-cert.pem
  
  
  
  peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52-1.peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52.default.svc.cluster.local:7051:
  
  
    
    url: grpcs://124.70.83.92:30606
    
    grpcOptions:
      ssl-target-name-override: peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52-1.peer-78c4b22104de75db92a172ae8fe5e9c6240d2c52.default.svc.cluster.local
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: C:\Users\86153\Desktop\javasdkdemo_src\config/78c4b22104de75db92a172ae8fe5e9c6240d2c52.peer/msp/tlscacerts/tlsca.78c4b22104de75db92a172ae8fe5e9c6240d2c52-cert.pem
  
